#!/bin/bash
# Spec Coding Multi-Agent Skill - Quick Start
# Usage: ./spec-coding-init.sh [project-name] [language]

set -e

PROJECT_NAME=${1:-"MyProject"}
LANGUAGE=${2:-"cpp"}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         Spec Coding Multi-Agent Skill - Quick Start          ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Project: $PROJECT_NAME"
echo "Language: $LANGUAGE"
echo ""

# Create project directory
PROJECT_DIR="./$PROJECT_NAME"
if [ -d "$PROJECT_DIR" ]; then
    echo "⚠️  Directory $PROJECT_DIR already exists"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

echo "📁 Creating project structure..."

# Create directories
mkdir -p {context/{requirements,framework,tasks},specs/{requirements,architecture,interface},src,tests/{unit,integration},scripts}

# Create initial files
cat > README.md << 'EOF'
# Project: PROJECT_NAME

Generated by Spec Coding Multi-Agent Skill

## Project Structure

```
.
├── context/           # Shared Architecture Context
│   ├── requirements/  # Clarified requirements
│   ├── framework/     # System architecture
│   └── tasks/         # Task decomposition
├── specs/            # Detailed specifications
│   ├── requirements/ # FR/NFR documents
│   ├── architecture/ # ADRs
│   └── interface/    # Interface specs
├── src/              # Implementation
├── tests/            # Test suite
└── harness.yaml      # Validation configuration
```

## Workflow Status

- [ ] Phase 1: Requirement Clarification
- [ ] Phase 2: Framework Design
- [ ] Phase 3: Task Decomposition
- [ ] Phase 4: Spec Authoring
- [ ] Phase 5: Harness Configuration
- [ ] Phase 6: Parallel Coding
- [ ] Phase 7: Self-Certification

## Quick Start

1. Start the workflow:
   ```bash
   python3 ../spec-coding-workflow.py init --project-name PROJECT_NAME --language LANGUAGE
   ```

2. Monitor progress in context/state.yaml

3. Review outputs at each checkpoint
EOF

sed -i.bak "s/PROJECT_NAME/$PROJECT_NAME/g" README.md
sed -i.bak "s/LANGUAGE/$LANGUAGE/g" README.md
rm README.md.bak

# Create .gitignore
cat > .gitignore << 'EOF'
# Build
build/
cmake-build-*/
*.o
*.a
*.so

# IDE
.vscode/
.idea/
*.swp

# Context state (auto-generated)
context/state.yaml

# Logs
logs/
*.log

# Coverage
coverage/
*.gcda
*.gcno
EOF

# Create initial context state
cat > context/state.yaml << EOF
project:
  name: "$PROJECT_NAME"
  language: "$LANGUAGE"
  created_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  status: "initialized"
  current_phase: null

phases: {}

global_state:
  modules: {}
  dependencies: []
  active_agents: 0

event_bus:
  subscriptions: []
  history: []
EOF

echo "✅ Project structure created"
echo ""
echo "Next steps:"
echo ""
echo "1. Define your project:"
echo "   Edit PROJECT_DESCRIPTION.txt with your requirements"
echo ""
echo "2. Start the workflow:"
echo "   cd $PROJECT_DIR"
echo "   python3 $SCRIPT_DIR/spec-coding-workflow.py init \\"
echo "       --project-name $PROJECT_NAME \\"
echo "       --language $LANGUAGE \\"
echo "       --description \"Your project description\""
echo ""
echo "3. Or start step-by-step:"
echo "   # Agent 1: Requirement Clarification"
echo "   python3 $SCRIPT_DIR/agent-1-clarify.py"
echo ""
echo "📖 Documentation: $SCRIPT_DIR/../SKILL.md"
echo ""
echo "Good luck! 🚀"
